import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SearchComponent from "@/components/layout/search";
import SideBar from "@/components/layout/sidebar";
import Footer from "@/components/layout/Footer";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WORKSYNC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} backdrop-blur-md bg-black rounded-3xl max-w-[1920px] h-screen`}
      >
        <div className="glassmorphism rounded-3xl h-[95vh] xl:m-3 lg:m-3 shadow-xl">
          <div className="grid xl:grid-cols-[15rem,1fr] lg:grid-cols-[15rem,1fr]">
            <SearchComponent />
            <SideBar />
            <main className="flex flex-col justify-center items-center">
              {children}
              <Toaster
                toastOptions={{ style: { background: "#0f172a" } }}
                position="top-center"
                reverseOrder={false}
              />
            </main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
